### PR TITLE
Upgrade to eslint 4

### PR DESCRIPTION
**Pull request by peterudo**
I'm not sure about the `objectLiteral*` properties. I can't really find anything about them in the ESLint docs.

Anyone know where they come from?

### CODE REVIEW

**Comment by pahen** [comment]
Old stuff? http://eslint.org/docs/user-guide/migrating-to-2.0.0#language-options

**Comment by peterudo** [comment]
Looks like using `ecmaVersion: 6` is enough. Want me to remove them, then @pahen?

**Comment by pahen** [comment]
Sounds good.

**Comment by gunnarlium** [comment]
You should also update the README to remove ES5 info (perhaps with a note that ES5 support was removed in this version. The commit message should also mention removing ES5.

**Comment by peterudo** [comment]
OK now @gunnarlium ?

**Pull request merged**
